### ISSUE TITLE
Modernization scanner not giving the results of list of site collection which are using the Classic workflows[BUG]

### ISSUE THREAD

**Issue by praveengovulakonda** [pnp/sp-dev-modernization#551]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

Modernization Scanner:  After connected with the Modernization scanner using the SharePoint online administrator credentials selected the option "Select CSV Sites File" . Started scanning showing few sites as running after few minutes nothing
![Scanner Output](https://user-images.githubusercontent.com/15153106/98905617-b81bc000-24e1-11eb-8e29-bd2f4cd418e0.JPG)
 is happening but in command prompt keep showing it is in progress saying "Retrieving a batch of up to 500 search results" even after many hours showing the same message but nothing is happening. 

#### Expected or Desired Behavior

 Should generate the excel sheet with a list of sites that are using the classic workflow usage.
#### Observed Behavior

Keep Showing the message "Retrieving a batch of up to 500 search results" for hours, but nothing has happened.

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @praveengovulakonda : Can you please disable the search option when scanning by checking the "Don't use search to get the site/page usage information and don't export that data" box. Also can you let me know if that fixes things. 

To scan a large tenant it's recommended to use an App-Only auth approach as credentials typically have limited access + using MFA only let's the scanner work for 1 hour due to the token lifetime. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner#step-2-preparing-for-a-scan

**Comment by praveengovulakonda** [comment]
Hello @jansenbe thank you for your reply.

I will check and get back to you.

**Comment by jansenbe** [comment]
Closing per no response for a long time.
